name: Teste
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Sobe o docker
        run: docker compose up -d

      - name: Build app
        run: mvn clean install

      - name: Run tests
        run: mvn test
