name: Teste
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Sobe o docker
        uses: docker-compose up -d

      - name: Build app
        run: mvn clean install

      - name: Run tests
        run: mvn test
